esphome:
  name: gvret
  friendly_name: GVRET

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
- source: github://hencou/esphome_gvret
  components: [canbus_gvret]
  refresh: 0s
  
# Enable Home Assistant API
api:

ota:
  - platform: esphome

# Enable logging
logger:
  level: WARN

wifi:
  ssid: !secret wifi_ssidC
  password: !secret wifi_passwordC

# Example based on Olimex ESP32-EVB Board
canbus:
  - platform: esp32_can
    id: can1
    can_id: 100
    rx_pin: GPIO35
    tx_pin: GPIO5
    bit_rate: 1000KBPS

canbus_gvret:
  can:
  - canbus_id: can1
