esphome:
  name: gvret
  friendly_name: GVRET

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
- source: github://hencou/esphome_gvret
  components: [canbus_gvret]
  refresh: 0s

# Example based on Olimex ESP32-EVB Board
canbus:
- platform: esp32_can
  id: my_canbus
  tx_pin: GPIO5
  rx_pin: GPIO35
  can_id: 0
  bit_rate: 1000kbps

- platform: canbus_gvret
  id: gvret
  can_id: 0
  canbus_id: my_canbus
        